name: Artifact Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create a file
        run: echo "This is Mano's artifact file 🎉" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt

  consume:
    runs-on: ubuntu-latest
    needs: build   # wait until build job finishes
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./downloaded

      - name: Show downloaded file
        run: cat ./downloaded/artifact.txt
